Modified installation script to work out of the box. Modified run_tests to be able to use WxH filenames in addition to W_H.

diff --git a/run_tests b/run_tests
--- a/run_tests
+++ b/run_tests
@@ -11,10 +11,25 @@ for sourcefile in $@; do
   # filename format: <path>/<clip_name>_<width>_<height>_<frame_rate>.yuv
   pathless=$(basename ${sourcefile})
   clip_stem=${pathless%.*}
-  part=($(echo $clip_stem | tr "_" "\n"))
-  width=${part[1]}
-  height=${part[2]}
-  frame_rate=${part[3]}
+  case $clip_stem in
+      *_*_*_*)
+          part=($(echo $clip_stem | tr "_" "\n"))
+          width=${part[1]}
+          height=${part[2]}
+          frame_rate=${part[3]}
+          ;;
+      *_*x*_*)
+          part=($(echo $clip_stem | tr "_" "\n"))
+          wh=($(echo ${part[1]} | tr "x" "\n"))
+          width=${wh[0]}
+          height=${wh[1]}
+          frame_rate=${part[2]}
+          ;;
+      default)
+          echo "Cannot decipher file pattern $pathless"
+          exit 1
+          ;;
+  esac
 
   echo "Clip $clip_stem"
   # Detecting test dirs by looking for the file name "measurer". Somewhat
